:wrench: move presets into provider
aol/angular-dayparts pull request #3
Opened 2017-01-31 19:39 UTC by tkraak

2017-02-01 10:49 UTC, FrenchDilettante requested changes

2017-02-01 10:49 UTC, manudwarf commented on src/angular-dayparts.js
> +      {"value":"custom", "label":"Custom", disabled: true}
Should it be disabled by default?

2017-02-01 10:49 UTC, manudwarf commented on src/template.html
> +  <select class="form-control" ng-model="selectedPresetItem" ng-options="item.value as item.label disable when item.disabled for item in presetItems" ng-change="selectedPresetItemChanged()"></select>
This is not a related change to presets. Although, it could be an additional property on the config provider :)

2017-02-01 13:30 UTC, tkraak commented on src/angular-dayparts.js
> +      {"value":"custom", "label":"Custom", disabled: true}
The demo in this repo is set up for AngularJS `1.6.1`, which means `disabled: true` should be the default ⚡️ .

2017-02-01 15:18 UTC, tkraak commented on src/template.html
> +  <select class="form-control" ng-model="selectedPresetItem" ng-options="item.value as item.label disable when item.disabled for item in presetItems" ng-change="selectedPresetItemChanged()"></select>
I moved this into the config provider, thx!

2017-02-02 17:13 UTC, FrenchDilettante approved these changes

2017-02-02 17:25 UTC, merged